# Generated by Django 3.1.7 on 2024-02-27 13:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IndiceSante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_national', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='Le numéro national doit contenir exactement 11 chiffres.')])),
                ('adresse_postale', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('commune', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Belgique', max_length=100)),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Le numéro de téléphone doit être entré au format '+999999999'. Jusqu'à 15 chiffres autorisés.")])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FraisExtraordinaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('medical', 'Médical et paramédical'), ('scolaire', 'Formation scolaire'), ('developpement', 'Développement personnel et épanouissement')], max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_extraordinaires', to='core.enfant')),
            ],
        ),
        migrations.AddField(
            model_name='enfant',
            name='parents',
            field=models.ManyToManyField(related_name='enfants', to='core.Profile'),
        ),
        migrations.CreateModel(
            name='Correspondance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('parent_emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondances_envoyees', to='core.profile')),
                ('parent_recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondances_recues', to='core.profile')),
            ],
        ),
    ]
