# Generated by Django 5.0.3 on 2024-06-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_paymentcategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcategory',
            name='type',
            field=models.CharField(choices=[('medical', 'Médicale'), ('schooling', 'Scolarité'), ('child development', 'Développement enfant'), ('other', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='category',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Payments.paymentcategory'),
            preserve_default=False,
        ),
    ]
