# Generated by Django 5.0.3 on 2024-04-04 20:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], default='X', max_length=1, null=True)),
                ('first_name', models.CharField(blank=True, default='test AnonymousUser', max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')], verbose_name='email address')),
                ('national_number_raw', models.CharField(blank=True, max_length=11, null=True)),
                ('national_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('telephone', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.TextField(blank=True, max_length=70, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('magistrat', 'Magistrat'), ('parent', 'Parent')], default='parent', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagistratParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magistrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_parents', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_magistrats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('magistrat', 'parent')},
            },
        ),
    ]
